app = "audacioustux-omniroute"
primary_region = "sin"
swap_size_mb = 512

[build]
  image = "diegosouzapw/omniroute:3.8.45"

[env]
  DATA_DIR = "/app/data"
  HOSTNAME = "0.0.0.0"
  PORT = "20128"

[[mounts]]
  source = "omniroute_data"
  destination = "/app/data"

[http_service]
  internal_port = 20128
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
